-- ============ CATALOG ============
CREATE TABLE public.catalog_items (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL CHECK (category IN ('look','cenario','maquiagem','cabelo','pose','iluminacao','acessorio')),
  name TEXT NOT NULL,
  image_url TEXT,
  color TEXT,
  style TEXT,
  tags TEXT[] NOT NULL DEFAULT '{}',
  ai_description TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.catalog_items TO authenticated;
GRANT ALL ON public.catalog_items TO service_role;
ALTER TABLE public.catalog_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "catalog_items_admin_all" ON public.catalog_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============ STATUS OPTIONS ============
CREATE TABLE public.order_status_options (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_status_options TO authenticated;
GRANT ALL ON public.order_status_options TO service_role;
ALTER TABLE public.order_status_options ENABLE ROW LEVEL SECURITY;
CREATE POLICY "status_admin_all" ON public.order_status_options FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============ ORDERS ============
CREATE TABLE public.orders (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  order_number INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) NOT NULL UNIQUE,
  client_name TEXT NOT NULL,
  client_phone TEXT NOT NULL DEFAULT '',
  photo_count INTEGER NOT NULL DEFAULT 10,
  package_label TEXT,
  status TEXT NOT NULL DEFAULT 'Aguardando cliente montar ensaio',
  identity_photos_received BOOLEAN NOT NULL DEFAULT false,
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('baixa','normal','alta')),
  due_date DATE,
  internal_notes TEXT NOT NULL DEFAULT '',
  public_token UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "orders_admin_all" ON public.orders FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============ ORDER CONFIG ============
CREATE TABLE public.order_configs (
  order_id UUID NOT NULL PRIMARY KEY REFERENCES public.orders(id) ON DELETE CASCADE,
  session_type TEXT,
  session_subtype TEXT,
  framing TEXT,
  outfit_mode TEXT,
  makeup TEXT,
  hair TEXT,
  color_palette TEXT,
  lighting_mood TEXT,
  visible_text_answer TEXT NOT NULL DEFAULT '',
  special_notes TEXT NOT NULL DEFAULT '',
  category_answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  current_step INTEGER NOT NULL DEFAULT 0,
  confirmed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_configs TO authenticated;
GRANT ALL ON public.order_configs TO service_role;
ALTER TABLE public.order_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "order_configs_admin_all" ON public.order_configs FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============ ORDER ITEMS ============
CREATE TABLE public.order_items (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  catalog_item_id UUID NOT NULL REFERENCES public.catalog_items(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (order_id, catalog_item_id, role)
);
CREATE INDEX order_items_order_id_idx ON public.order_items(order_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;
GRANT ALL ON public.order_items TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "order_items_admin_all" ON public.order_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============ TIMESTAMP TRIGGER ============
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER catalog_items_updated_at BEFORE UPDATE ON public.catalog_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER order_configs_updated_at BEFORE UPDATE ON public.order_configs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============ SEED: STATUS ============
INSERT INTO public.order_status_options (label, position) VALUES
  ('Aguardando cliente montar ensaio', 1),
  ('Ensaio montado', 2),
  ('Aguardando fotos de identidade', 3),
  ('Pronto para produção', 4),
  ('Em produção', 5),
  ('Entregue', 6);

-- ============ SEED: CATALOG ============
INSERT INTO public.catalog_items (code, category, name, color, style, tags, ai_description, position) VALUES
('V001','look','Vestido vermelho glamouroso','Vermelho','glamour','{vestido,noite,glamour}','Vestido longo em cetim vermelho rubi profundo, caimento fluido e levemente pesado, com brilho acetinado que reflete a luz nas dobras. Decote V discreto, alças finas, cintura marcada e fenda lateral sutil. Tecido sem estampa, textura lisa e uniforme, com sombras suaves nas pregas verticais do comprimento.',1),
('V002','look','Terno branco minimalista','Branco','minimalista','{alfaiataria,corporativo,clean}','Conjunto de alfaiataria em lã fria branco off-white, blazer de corte reto com ombro estruturado e um único botão, calça de cintura alta com prega central bem definida. Por baixo, camiseta de algodão branca lisa. Acabamento impecável, sem amassados, textura mate discreta.',2),
('V003','look','Vestido de seda nude fluido','Nude','romântico','{seda,romantico,leve}','Vestido midi em seda pura tom nude rosado, tecido leve e translúcido em movimento, com drapeado suave na cintura e barra assimétrica. Brilho discreto e natural da seda, dobras finas que criam gradientes sutis de sombra sobre o tecido.',3),
('V004','look','Traje de gala preto','Preto','editorial','{gala,preto,formal}','Vestido de gala longo em crepe preto absoluto, ombro único estruturado, silhueta reta e alongada, sem brilho — textura mate densa que absorve a luz e cria contorno limpo contra o fundo. Acabamento de alta costura, sem adornos.',4),
('C001','cenario','Estúdio fundo bege liso','Bege','minimalista','{estudio,fundo,liso}','Estúdio fotográfico com ciclorama de papel bege areia, superfície perfeitamente lisa e sem emendas, leve gradiente de luz do centro para as bordas. Piso do mesmo tom, sem objetos de cena. Ambiente limpo, foco total na pessoa.',1),
('C002','cenario','Salão clássico com pé-direito alto','Neutro','editorial','{interno,classico,luxo}','Salão clássico europeu com paredes em boiserie branca envelhecida, pé-direito alto, piso de madeira em espinha de peixe, cortinas de linho pesado até o chão e uma grande janela lateral. Móveis discretos ao fundo, levemente desfocados, iluminação natural difusa entrando pela janela.',2),
('C003','cenario','Terraço ao pôr do sol','Dourado','romântico','{externo,poente,cidade}','Terraço aberto de concreto queimado ao fim da tarde, horizonte urbano difuso ao fundo em tons de laranja e lilás, luz dourada rasante vindo de trás e para a esquerda, plantas ornamentais em vasos de barro nas laterais, poeira de luz visível no ar.',3),
('M001','maquiagem','Maquiagem natural luminosa','Neutro','natural','{natural,clean,glow}','Maquiagem de pele leve e luminosa, acabamento acetinado com brilho natural nas maçãs do rosto, sobrancelhas penteadas sem preenchimento pesado, cílios definidos sem alongamento, boca em tom nude rosado hidratado. Nenhum contorno marcado.',1),
('M002','maquiagem','Maquiagem glam olhos esfumados','Preto','glamour','{glam,esfumado,noite}','Maquiagem de festa com olhos esfumados em marrom escuro e preto, cantos externos alongados, delineado difuso, cílios volumosos, pele com acabamento aveludado, iluminador discreto no arco da sobrancelha e no osso nasal, boca em tom nude fechado.',2),
('H001','cabelo','Cabelo solto com ondas suaves','Neutro','romântico','{solto,ondas,natural}','Penteado solto com ondas largas e suaves feitas com modelador grosso, repartição central, volume moderado na raiz, fios com brilho saudável e movimento natural caindo sobre os ombros. Acabamento sem frizz, aspecto leve.',1),
('H002','cabelo','Coque baixo polido','Neutro','minimalista','{preso,coque,clean}','Coque baixo bem polido na nuca, fios totalmente penteados para trás com brilho de gel discreto, repartição limpa, sem mechas soltas, silhueta escultural que valoriza o colo e a linha do maxilar.',2),
('L001','iluminacao','Luz suave de softbox três pontos','Neutro','clean','{estudio,softbox,suave}','Iluminação de estúdio em três pontos: softbox principal grande a 45 graus da pessoa e ligeiramente acima da linha dos olhos, rebatedor branco do lado oposto preenchendo sombras, e luz de fundo suave separando a silhueta do cenário. Sombras macias e degradê gentil, contraste médio-baixo.',1),
('L002','iluminacao','Luz dourada de fim de tarde','Dourado','romântico','{natural,dourada,poente}','Luz natural de fim de tarde, sol baixo entrando lateralmente e por trás, criando contorno dourado nos cabelos e nos ombros, sombras alongadas e quentes, leve halo de luz difusa na borda do quadro, temperatura de cor quente e atmosfera suave.',2),
('L003','iluminacao','Luz dramática de alto contraste','Preto','editorial','{dramatica,contraste,editorial}','Iluminação dramática de fonte única e dura, posicionada lateralmente, gerando contraste alto entre luz e sombra, meio rosto em penumbra controlada, fundo escuro sem informação, recorte nítido dos volumes do rosto e do corpo.',3),
('P001','pose','De pé, olhar frontal e ombros alinhados','Neutro','clean','{pe,frontal,classica}','De pé, corpo alinhado à câmera com ombros levemente girados, peso apoiado em uma perna, braços relaxados ao longo do corpo com as mãos naturais. Rosto sempre voltado frontalmente para a câmera, queixo na linha do horizonte, expressão serena.',1),
('P002','pose','Sentada com tronco inclinado à frente','Neutro','editorial','{sentada,editorial}','Sentada em banco baixo, tronco levemente inclinado à frente, antebraços apoiados nas coxas, coluna alongada. Rosto sempre voltado frontalmente para a câmera, olhar direto na lente, expressão tranquila e confiante.',2),
('P003','pose','Caminhando em direção à câmera','Neutro','editorial','{movimento,caminhada}','Passo à frente em direção à câmera, uma perna adiantada, braços em movimento natural, tecido da roupa em leve deslocamento. Rosto sempre voltado frontalmente para a câmera, olhar na lente, expressão leve.',3),
('P004','pose','Mãos no rosto, enquadramento de rosto e ombros','Neutro','romântico','{retrato,maos}','Retrato de rosto e ombros com uma das mãos tocando levemente a lateral do rosto, dedos relaxados e sem tensão, ombro contrário levemente baixo. Rosto sempre voltado frontalmente para a câmera, olhar direto, expressão delicada.',4),
('A001','acessorio','Brincos dourados geométricos','Dourado','minimalista','{joia,brinco,dourado}','Brincos de ouro amarelo escovado, formato geométrico retangular médio, acabamento mate com reflexo suave, sem pedras. Peso visual discreto, alinhados junto ao maxilar.',1),
('A002','acessorio','Colar de pérolas clássico','Branco','clássico','{joia,perola,classico}','Colar curto de pérolas naturais brancas de tamanho uniforme, brilho perolado suave, fecho discreto, assentado na base do colo.',2),
('A003','acessorio','Véu longo de tule','Branco','romântico','{casamento,veu}','Véu de tule francês branco, comprimento longo até o chão, tecido ultrafino e translúcido com caimento leve, borda sem acabamento aparente, movimento suave ao vento.',3),
('A004','acessorio','Buquê de flores do campo','Multicor','romântico','{casamento,flores}','Buquê de flores do campo em tons brancos, creme e verde, amarração natural com fita de cetim cru, hastes visíveis, formato solto e assimétrico.',4);

-- ============ STORAGE POLICIES ============
CREATE POLICY "catalog_images_public_read" ON storage.objects FOR SELECT USING (bucket_id = 'catalog');
CREATE POLICY "catalog_images_admin_write" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'catalog');
CREATE POLICY "catalog_images_admin_update" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'catalog');
CREATE POLICY "catalog_images_admin_delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'catalog');